# -*- coding: utf-8 -*-
"""Introducción_sistemas_practica3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tUcHaX4xaBm7LcfNCbYf1d0zDE2laIkm
"""

import pandas as pd

#Lectura y extraccion
elementos = pd.read_csv('Lista_Actividades.csv', header=0)
elementos_dic = elementos.to_dict('series')

elementos

#Estructuracion de las variables 
Actividades = elementos_dic['Actividad']
Digitos1 = elementos_dic['Digito1']
Digitos2 = elementos_dic['Digito2']
Digitos3 = elementos_dic['Digito3']

Actividades

Actividades[3]

#Ejemplo de operacion
for i  in range(4):
  if (Actividades[i] == 'Suma '):
    Resultado = float(Digitos1[i] + Digitos2[i] + Digitos3[i])
    print("El resultado de la actividad 1 (Suma) es: ", Resultado)
    calif1 = input("Asigne una calificación a la actividad (Suma): ")
  elif (Actividades[i] == 'Resta'):
    Resultado = float(Digitos1[i] - Digitos2[i] - Digitos3[i])
    print("El resultado de la actividad 2 (Resta) es: ", Resultado)
    calif2 = input("Asigne una calificación a la actividad (Resta): ")
  elif (Actividades[i] == 'Multiplicación'):
    Resultado = float(Digitos1[i] * Digitos2[i] * Digitos3[i])
    print("El resultado de la actividad 3 (Multiplicación) es: ", Resultado)
    calif3 = input("Asigne una calificación a la actividad (Multiplicación): ")
  elif (Actividades[i] == 'División'):
    Resultado = float(Digitos1[i] / Digitos2[i] / Digitos3[i])
    print("El resultado de la actividad 4 (División) es: ", Resultado)
    calif4 = input("Asigne una calificación a la actividad (Division): ")
  else:
    print(Actividades[i])
print("-------------------------------------------")
print("Las calificaciones de las actividades son: ")
print("- Suma: ", calif1)
print("- Resta: ", calif2)
print("- Multiplicación: ", calif3)
print("- Division: ", calif4)